[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pycmake"
version = "0.1.0"
description = "A build system for C++."
readme = "README.md"
requires-python = ">=3.6"
license = "MIT"

[project.urls]